<a href="https://colab.research.google.com/github/fatmas1982/Neural-network-implementation-from-scratch/blob/main/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Coding Our First Neurons**

**حاصل الضرب القياسي بدلالة المكونات**


الضرب القياسي scalar product (a single value/number)

او الضرب النقطي dot product (element wise)

In [76]:
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

In [78]:
output=(inputs[0]*weights[0]+
        inputs[1]*weights[1]+
        inputs[2]*weights[2] +
        bias) 

print(output)

2.3


In [79]:
import numpy as np


In [80]:
output_np=np.dot(inputs,weights)+bias

In [81]:
output_np

2.3

##**A Layer of Neurons with NumPy**

In [1]:
import numpy as np


In [82]:
i=[1,2,3,2.5]
w=[[.2,.8,-.5,1],
   [.5,-.91,.26,-.5],
   [-.26,-.27,.17,.87]]
b=[2,3,.5]

In [87]:
i

[1, 2, 3, 2.5]

In [84]:
w

[[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

In [86]:
np.transpose(w)

array([[ 0.2 ,  0.5 , -0.26],
       [ 0.8 , -0.91, -0.27],
       [-0.5 ,  0.26,  0.17],
       [ 1.  , -0.5 ,  0.87]])

In [83]:
i

[1, 2, 3, 2.5]

In [88]:
o=np.dot(i,np.transpose(w))+b

In [89]:
o

array([4.8  , 1.21 , 2.385])

In [75]:
1*.2+2*.8+3*-.5+2.5*1+2

4.8

In [90]:
o=np.dot(w,i)+b

In [91]:
o

array([4.8  , 1.21 , 2.385])

##**A Batch of Data**

In [37]:
import numpy as np

In [24]:
a=[1,2,3]
print(type(a))
print(len(a))
print(a)
b=np.array(a)
print(type(b))
print(b)
print(b.shape)
print(b.size)
print(len(b))

<class 'list'>
3
[1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]
(3,)
3
3


In [25]:
c=np.expand_dims(a,axis=0)
print(type(c))
print(c)
print(c.shape)
print(c.size)
print(len(c))

<class 'numpy.ndarray'>
[[1 2 3]]
(1, 3)
3
1


In [51]:
d=np.expand_dims(c,axis=0)
print(type(d))
print(d)
print(d.shape)
print(d.size)
print(len(d))

<class 'numpy.ndarray'>
[[[1 2 3]]]
(1, 1, 3)
3
1


In [52]:
b.T

array([1, 2, 3])

In [53]:
np.transpose(b)

array([1, 2, 3])

In [28]:
c.T

array([[1],
       [2],
       [3]])

In [54]:
d

array([[[1, 2, 3]]])

In [55]:
d.T

array([[[1]],

       [[2]],

       [[3]]])

In [56]:
e=[1,2,3]
s=[2,3,4]
n=np.dot(e,s)
print(n, type(n))

20 <class 'numpy.int64'>


In [35]:

m=np.dot(np.array([e]),np.array([s]).T)
print(m, type(m)) #returned a matrix containing a single value.

[[20]] <class 'numpy.ndarray'>


###**A Layer of Neurons & Batch of Data w/ NumPy**

x+y+z  ,a+y+b,z+w+p

xyzabwp

In [76]:
inputs=[[1,2,3],[4,2,6],[3,8,9],[3,8,9],[4,2,6]] #x,y,x..etc 
weights=[[1,2,3]]#,[4,5,6],[7,8,9]]
bias=[1,2,3]

In [73]:
type(inputs)

list

In [69]:
len(inputs)

4

In [77]:
output=np.dot(inputs,np.transpose(weights))+bias

In [78]:
output

array([[15, 16, 17],
       [27, 28, 29],
       [47, 48, 49],
       [47, 48, 49],
       [27, 28, 29]])

In [46]:
type(output)

numpy.ndarray

In [47]:
type(inputs)

list